"""BenchHub category definitions for evaluation plans."""

# BenchHub Categories Configuration
BENCHHUB_COARSE_CATEGORIES = [
    "Art & Sports",
    "Culture",
    "HASS",
    "Science",
    "Social Intelligence",
    "Tech."
]

BENCHHUB_FINE_CATEGORIES = {
    "Art & Sports": [
        "Art & Sports/Architecture",
        "Art & Sports/Clothing",
        "Art & Sports/Education",
        "Art & Sports/Fashion",
        "Art & Sports/Festivals",
        "Art & Sports/Food",
        "Art & Sports/Language",
        "Art & Sports/Literature",
        "Art & Sports/Media",
        "Art & Sports/Music",
        "Art & Sports/Painting",
        "Art & Sports/Performing",
        "Art & Sports/Photography",
        "Art & Sports/Sculpture",
        "Art & Sports/Sports",
        "Art & Sports/Urban Eng.",
        "Art & Sports/arts&sports/animal",
        "Art & Sports/arts&sports/animal_life",
        "Art & Sports/arts&sports/animals",
        "Art & Sports/arts&sports/animation",
        "Art & Sports/arts&sports/anime",
        "Art & Sports/arts&sports/art",
        "Art & Sports/arts&sports/arts",
        "Art & Sports/arts&sports/artwork",
        "Art & Sports/arts&sports/barking",
        "Art & Sports/arts&sports/boat",
        "Art & Sports/arts&sports/branding",
        "Art & Sports/arts&sports/character",
        "Art & Sports/arts&sports/collecting",
        "Art & Sports/arts&sports/dance",
        "Art & Sports/arts&sports/design",
        "Art & Sports/arts&sports/digital_design",
        "Art & Sports/arts&sports/dog",
        "Art & Sports/arts&sports/dogs",
        "Art & Sports/arts&sports/drink",
        "Art & Sports/arts&sports/equestrian",
        "Art & Sports/arts&sports/fantasy",
        "Art & Sports/arts&sports/farming",
        "Art & Sports/arts&sports/fiction",
        "Art & Sports/arts&sports/fitness",
        "Art & Sports/arts&sports/flower",
        "Art & Sports/arts&sports/furniture",
        "Art & Sports/arts&sports/game",
        "Art & Sports/arts&sports/gaming",
        "Art & Sports/arts&sports/graphics",
        "Art & Sports/arts&sports/illustration",
        "Art & Sports/arts&sports/infographic",
        "Art & Sports/arts&sports/landscape",
        "Art & Sports/arts&sports/landscapes",
        "Art & Sports/arts&sports/nature",
        "Art & Sports/arts&sports/poetry",
        "Art & Sports/arts&sports/puzzle",
        "Art & Sports/arts&sports/reading",
        "Art & Sports/arts&sports/scenic",
        "Art & Sports/arts&sports/speech",
        "Art & Sports/arts&sports/toy",
        "Art & Sports/arts&sports/transportation",
        "Art & Sports/arts&sports/typography",
        "Art & Sports/arts&sports/urban",
        "Art & Sports/arts&sports/urban_art",
        "Art & Sports/arts&sports/urban_design",
        "Art & Sports/arts&sports/urban_environment",
        "Art & Sports/arts&sports/urban_life",
        "Art & Sports/arts&sports/urbanism",
        "Art & Sports/arts&sports/video_games",
        "Art & Sports/arts&sports/website",
        "Art & Sports/arts&sports/wine",
        "Art & Sports/arts&sports/zoology"
    ],
    "Culture": [
        "Culture/Celebration Holiday",
        "Culture/Clothing",
        "Culture/Daily Life",
        "Culture/Family",
        "Culture/Food",
        "Culture/Holiday",
        "Culture/Housing",
        "Culture/Leisure",
        "Culture/Tradition",
        "Culture/Work Life",
        "Culture/culture/attractions",
        "Culture/culture/friendship",
        "Culture/culture/hobbies",
        "Culture/culture/nature"
    ],
    "HASS": [
        "HASS/Administration",
        "HASS/Art & Sports",
        "HASS/Biology",
        "HASS/Celebration Holiday",
        "HASS/Cognitive Studies",
        "HASS/Culture",
        "HASS/Daily Life",
        "HASS/Economics",
        "HASS/Education",
        "HASS/Family",
        "HASS/Food",
        "HASS/Geography",
        "HASS/HASS",
        "HASS/History",
        "HASS/Language",
        "HASS/Law",
        "HASS/Literature",
        "HASS/Math",
        "HASS/Media",
        "HASS/Music",
        "HASS/Philosophy",
        "HASS/Physics",
        "HASS/Politics",
        "HASS/Psychology",
        "HASS/Religion",
        "HASS/Sports",
        "HASS/Tech.",
        "HASS/Trade",
        "HASS/Tradition",
        "HASS/Urban Eng.",
        "HASS/Welfare",
        "HASS/Work Life",
        "HASS/social&humanity/animal_welfare",
        "HASS/social&humanity/biography",
        "HASS/social&humanity/branding",
        "HASS/social&humanity/celebrity",
        "HASS/social&humanity/communication",
        "HASS/social&humanity/crime",
        "HASS/social&humanity/customer_support",
        "HASS/social&humanity/data_science",
        "HASS/social&humanity/database",
        "HASS/social&humanity/databases",
        "HASS/social&humanity/date",
        "HASS/social&humanity/dates",
        "HASS/social&humanity/datetime",
        "HASS/social&humanity/director",
        "HASS/social&humanity/drama",
        "HASS/social&humanity/environment",
        "HASS/social&humanity/fiction",
        "HASS/social&humanity/finance",
        "HASS/social&humanity/friendship",
        "HASS/social&humanity/health",
        "HASS/social&humanity/hero",
        "HASS/social&humanity/identity",
        "HASS/social&humanity/leadership",
        "HASS/social&humanity/library",
        "HASS/social&humanity/lifestyle",
        "HASS/social&humanity/management",
        "HASS/social&humanity/museum",
        "HASS/social&humanity/organizations",
        "HASS/social&humanity/privacy",
        "HASS/social&humanity/real_estate",
        "HASS/social&humanity/sociology",
        "HASS/social&humanity/technology",
        "HASS/social&humanity/transport",
        "HASS/social&humanity/transportation",
        "HASS/social&humanity/website",
        "HASS/social&humanity/workplace"
    ],
    "Science": [
        "Science/Astronomy",
        "Science/Atmospheric Science",
        "Science/Biology",
        "Science/Biomedical Eng.",
        "Science/Chemistry",
        "Science/Earth Science",
        "Science/Electrical Eng.",
        "Science/Geology",
        "Science/History",
        "Science/Language",
        "Science/Life Science",
        "Science/Math",
        "Science/Physics",
        "Science/Religion",
        "Science/Statistics",
        "Science/science/color",
        "Science/science/dna",
        "Science/science/dna2protein",
        "Science/science/numerology",
        "Science/science/plant"
    ],
    "Social Intelligence": [
        "Social Intelligence/Bias",
        "Social Intelligence/Commonsense",
        "Social Intelligence/Language",
        "Social Intelligence/Norms",
        "Social Intelligence/Value/Alignment",
        "Social Intelligence/misc/abstract",
        "Social Intelligence/misc/animal",
        "Social Intelligence/misc/cliche",
        "Social Intelligence/misc/color",
        "Social Intelligence/misc/diagnosis",
        "Social Intelligence/misc/durable",
        "Social Intelligence/misc/hate_crime",
        "Social Intelligence/misc/health",
        "Social Intelligence/misc/idiomatic_expression",
        "Social Intelligence/misc/norm",
        "Social Intelligence/misc/proverb",
        "Social Intelligence/misc/thinking",
        "Social Intelligence/misc/wellbeing"
    ],
    "Tech.": [
        "Tech./AI",
        "Tech./Aerospace Eng.",
        "Tech./Agricultural Eng.",
        "Tech./Biomedical Eng.",
        "Tech./Chemical Eng.",
        "Tech./Civil Eng.",
        "Tech./Coding",
        "Tech./Electrical Eng.",
        "Tech./Energy",
        "Tech./Environmental Eng.",
        "Tech./Food",
        "Tech./Geography",
        "Tech./IT",
        "Tech./Marine Eng.",
        "Tech./Materials Eng.",
        "Tech./Mechanics",
        "Tech./Nuclear Eng.",
        "Tech./Physics",
        "Tech./Urban Eng.",
        "Tech./tech/aircraft",
        "Tech./tech/airline",
        "Tech./tech/airlines",
        "Tech./tech/algorithm",
        "Tech./tech/animal",
        "Tech./tech/animal_welfare",
        "Tech./tech/animation",
        "Tech./tech/aquarium",
        "Tech./tech/automotive",
        "Tech./tech/aviation",
        "Tech./tech/azure",
        "Tech./tech/boat",
        "Tech./tech/cloud",
        "Tech./tech/communication",
        "Tech./tech/communications",
        "Tech./tech/cv",
        "Tech./tech/database",
        "Tech./tech/db",
        "Tech./tech/dice",
        "Tech./tech/ethereum",
        "Tech./tech/finance",
        "Tech./tech/financial",
        "Tech./tech/geo_loc",
        "Tech./tech/geolocation",
        "Tech./tech/graphics",
        "Tech./tech/ios",
        "Tech./tech/marine_biology",
        "Tech./tech/marine_eng",
        "Tech./tech/mobile",
        "Tech./tech/monitoring",
        "Tech./tech/network",
        "Tech./tech/ocr",
        "Tech./tech/office",
        "Tech./tech/programming",
        "Tech./tech/real_estate",
        "Tech./tech/remote_sensing",
        "Tech./tech/robotics",
        "Tech./tech/secure",
        "Tech./tech/security",
        "Tech./tech/transportation",
        "Tech./tech/uuid",
        "Tech./tech/vehicle",
        "Tech./tech/voice"
    ]
}