-- =============================================================================
-- BenchHub Plus — initial Supabase schema
-- =============================================================================
-- This migration recreates every table the SQLAlchemy models in apps/core/db.py
-- declare, plus the indexes, unique/check constraints, and the auto-`updated_at`
-- trigger that the ORM emulates with onupdate=NOW().
--
-- Apply with the Supabase CLI (`supabase migration up`) or paste into the
-- Supabase SQL editor. Tables are created in dependency order, so the file is
-- safe to re-run on a fresh project. `IF NOT EXISTS` guards mean it is also
-- idempotent against partially-created environments.
--
-- Note on row-level security: RLS is **disabled** by default below because the
-- backend (FastAPI) enforces tenant filtering at the ORM layer and uses a
-- single privileged service role to talk to Supabase. Enable RLS only if you
-- start exposing PostgREST/Realtime directly to end users — there is a
-- commented-out RLS template at the end of this file.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ---------------------------------------------------------------------------
-- Helper trigger function: keep `updated_at` in sync on row updates.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- organizations
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organizations (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_organizations_slug
    ON public.organizations (slug);

-- ---------------------------------------------------------------------------
-- workspaces
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.workspaces (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES public.organizations (id),
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_workspace_slug UNIQUE (organization_id, slug)
);

CREATE INDEX IF NOT EXISTS ix_workspaces_organization_id
    ON public.workspaces (organization_id);

-- ---------------------------------------------------------------------------
-- users
--   The `default_org_id` / `default_workspace_id` FKs are nullable so a
--   freshly created user can exist before their default workspace is
--   provisioned (see _ensure_default_workspace in apps/backend/routes/auth.py).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_id            VARCHAR(255) NOT NULL UNIQUE,
    email                VARCHAR(255) NOT NULL UNIQUE,
    email_verified       BOOLEAN NOT NULL DEFAULT FALSE,
    full_name            VARCHAR(255),
    picture_url          VARCHAR(500),
    is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    role                 VARCHAR(50) NOT NULL DEFAULT 'user',
    is_admin             BOOLEAN NOT NULL DEFAULT FALSE,
    default_org_id       INTEGER REFERENCES public.organizations (id),
    default_workspace_id INTEGER REFERENCES public.workspaces (id),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_users_google_id          ON public.users (google_id);
CREATE INDEX IF NOT EXISTS idx_users_email              ON public.users (email);
CREATE INDEX IF NOT EXISTS idx_users_role               ON public.users (role);
CREATE INDEX IF NOT EXISTS idx_users_default_org        ON public.users (default_org_id);
CREATE INDEX IF NOT EXISTS idx_users_default_workspace  ON public.users (default_workspace_id);

-- ---------------------------------------------------------------------------
-- workspace_memberships
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.workspace_memberships (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id INTEGER NOT NULL REFERENCES public.workspaces (id),
    user_id      INTEGER NOT NULL REFERENCES public.users (id),
    role         VARCHAR(50) NOT NULL DEFAULT 'member',
    is_owner     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_workspace_member UNIQUE (workspace_id, user_id)
);

CREATE INDEX IF NOT EXISTS ix_workspace_memberships_workspace_id
    ON public.workspace_memberships (workspace_id);
CREATE INDEX IF NOT EXISTS ix_workspace_memberships_user_id
    ON public.workspace_memberships (user_id);

-- ---------------------------------------------------------------------------
-- leaderboard_cache
--   Public view of leaderboard rows. `quarantined` and `deleted_at` let
--   moderators hide entries without losing history.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.leaderboard_cache (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name    VARCHAR(255) NOT NULL,
    language      VARCHAR(50)  NOT NULL,
    subject_type  VARCHAR(100) NOT NULL,
    task_type     VARCHAR(100) NOT NULL,
    score         DOUBLE PRECISION NOT NULL,
    quarantined   BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_updated  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_leaderboard_cache_entry UNIQUE
        (model_name, language, subject_type, task_type)
);

-- ---------------------------------------------------------------------------
-- evaluation_tasks
--   `task_id` is the externally visible Celery task UUID and serves as PK.
--   `status` is constrained to the same enum the backend recognises.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.evaluation_tasks (
    task_id          VARCHAR(255) PRIMARY KEY,
    user_id          INTEGER REFERENCES public.users (id),
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    plan_details     TEXT,
    request_payload  TEXT,
    result           TEXT,
    error_message    TEXT,
    error_log        TEXT,
    policy_tags      TEXT,
    model_count      INTEGER,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at     TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT check_status_values
        CHECK (status IN ('PENDING','STARTED','SUCCESS','FAILURE','CANCELLED','HOLD'))
);

CREATE INDEX IF NOT EXISTS ix_evaluation_tasks_user_id
    ON public.evaluation_tasks (user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status_created
    ON public.evaluation_tasks (status, created_at);

DROP TRIGGER IF EXISTS trg_evaluation_tasks_updated_at ON public.evaluation_tasks;
CREATE TRIGGER trg_evaluation_tasks_updated_at
    BEFORE UPDATE ON public.evaluation_tasks
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- experiment_samples
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.experiment_samples (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt         TEXT          NOT NULL,
    answer         TEXT          NOT NULL,
    skill_label    VARCHAR(100)  NOT NULL,
    target_label   VARCHAR(100)  NOT NULL,
    subject_label  VARCHAR(100)  NOT NULL,
    format_label   VARCHAR(100)  NOT NULL,
    dataset_name   VARCHAR(100)  NOT NULL,
    meta_data      TEXT,
    correctness    DOUBLE PRECISION NOT NULL,
    timestamp      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- (No indexes are declared on experiment_samples in the SQLAlchemy model.)

-- ---------------------------------------------------------------------------
-- model_credentials
--   `encrypted_api_key` is Fernet-encrypted by apps/core/security.py before
--   it lands here; the DB never sees plaintext keys.
--   TODO (multi-tenancy): add a `user_id` / `workspace_id` column once the
--         backend is ready to scope credentials per tenant.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.model_credentials (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name         VARCHAR(255) NOT NULL,
    model_type         VARCHAR(100),
    api_base           VARCHAR(255) NOT NULL,
    credential_hash    VARCHAR(128) NOT NULL,
    encrypted_api_key  TEXT NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ,
    last_used_at       TIMESTAMPTZ,
    CONSTRAINT uq_model_credentials_hash UNIQUE (credential_hash)
);

-- ---------------------------------------------------------------------------
-- benchmark_samples
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.benchmark_samples (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language        VARCHAR(50)  NOT NULL,
    subject_type    VARCHAR(100) NOT NULL,
    task_type       VARCHAR(100) NOT NULL,
    problem_type    VARCHAR(50),
    benchmark_name  VARCHAR(200),
    prompt          TEXT NOT NULL,
    options         TEXT,
    answer_str      VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS ix_benchmark_samples_language
    ON public.benchmark_samples (language);
CREATE INDEX IF NOT EXISTS ix_benchmark_samples_subject_type
    ON public.benchmark_samples (subject_type);
CREATE INDEX IF NOT EXISTS ix_benchmark_samples_task_type
    ON public.benchmark_samples (task_type);
CREATE INDEX IF NOT EXISTS idx_bench_samples_lang_subj
    ON public.benchmark_samples (language, subject_type);
CREATE INDEX IF NOT EXISTS idx_bench_samples_task
    ON public.benchmark_samples (task_type);

-- ---------------------------------------------------------------------------
-- audit_logs
--   Append-only history of admin actions. `meta` is a JSON string blob —
--   keep it TEXT for parity with SQLAlchemy; promote to JSONB later if you
--   need indexed queries.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER REFERENCES public.users (id),
    action       VARCHAR(100) NOT NULL,
    resource     VARCHAR(100) NOT NULL,
    resource_id  VARCHAR(255),
    meta         TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_audit_logs_user_id
    ON public.audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_resource
    ON public.audit_logs (resource, created_at);

-- ---------------------------------------------------------------------------
-- evaluation_drafts
--   Conversational draft state. `spec` and `messages` are JSON-encoded TEXT
--   blobs maintained by the chat planner.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.evaluation_drafts (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           INTEGER NOT NULL REFERENCES public.users (id),
    title             VARCHAR(255),
    spec              TEXT NOT NULL DEFAULT '{}',
    messages          TEXT NOT NULL DEFAULT '[]',
    status            VARCHAR(32) NOT NULL DEFAULT 'draft',
    launched_task_id  VARCHAR(255),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_evaluation_drafts_user_id
    ON public.evaluation_drafts (user_id);
CREATE INDEX IF NOT EXISTS ix_evaluation_drafts_status
    ON public.evaluation_drafts (status);
CREATE INDEX IF NOT EXISTS idx_evaluation_drafts_user_status
    ON public.evaluation_drafts (user_id, status);
CREATE INDEX IF NOT EXISTS idx_evaluation_drafts_updated_at
    ON public.evaluation_drafts (updated_at);

DROP TRIGGER IF EXISTS trg_evaluation_drafts_updated_at ON public.evaluation_drafts;
CREATE TRIGGER trg_evaluation_drafts_updated_at
    BEFORE UPDATE ON public.evaluation_drafts
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row-level security (deny-by-default)
-- ---------------------------------------------------------------------------
-- Supabase auto-exposes every table in `public` through the PostgREST API
-- (anon + authenticated roles). Without RLS, anyone holding the project's
-- public anon key could SELECT model_credentials, evaluation_drafts, etc.
-- We turn RLS ON with no policies, which means:
--   * anon / authenticated roles  → all queries denied (correct default)
--   * service_role (bypassrls)    → unaffected (the FastAPI backend keeps
--                                   full access via the service-role conn)
-- If you later want to expose a table directly to authenticated clients,
-- add a CREATE POLICY for it (template at the bottom of this file).
ALTER TABLE public.organizations         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspaces            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard_cache     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evaluation_tasks      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiment_samples    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.model_credentials     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.benchmark_samples     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evaluation_drafts     ENABLE ROW LEVEL SECURITY;

COMMIT;

-- =============================================================================
-- Optional: per-user RLS policies (only needed if you talk to PostgREST
-- directly from the client with the authenticated role)
-- =============================================================================
-- Today the FastAPI backend uses the service_role connection, which bypasses
-- RLS entirely, so the deny-by-default state above is exactly what we want.
-- The block below is a starting point if you ever wire `@supabase/supabase-js`
-- into the frontend — adjust `auth.uid()::text` to whatever id-mapping
-- convention you adopt (Supabase Auth user IDs vs. our public.users.id).
--
-- CREATE POLICY tasks_owner_read ON public.evaluation_tasks
--     FOR SELECT USING (user_id::text = auth.uid()::text);
-- CREATE POLICY tasks_owner_write ON public.evaluation_tasks
--     FOR ALL USING (user_id::text = auth.uid()::text)
--     WITH CHECK (user_id::text = auth.uid()::text);
--
-- CREATE POLICY drafts_owner ON public.evaluation_drafts
--     FOR ALL USING (user_id::text = auth.uid()::text)
--     WITH CHECK (user_id::text = auth.uid()::text);
-- =============================================================================
